# Generated by Django 5.0.4 on 2024-06-03 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_courseenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('monday', models.JSONField(default=list)),
                ('tuesday', models.JSONField(default=list)),
                ('wednesday', models.JSONField(default=list)),
                ('thursday', models.JSONField(default=list)),
                ('friday', models.JSONField(default=list)),
                ('saturday', models.JSONField(default=list)),
                ('sunday', models.JSONField(default=list)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='course.course')),
            ],
        ),
    ]
