# Generated by Django 5.0.4 on 2024-06-03 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_coursetimetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('video', 'Video'), ('file', 'File'), ('audio', 'Audio'), ('image', 'Image')], max_length=10)),
                ('file', models.FileField(upload_to='course_materials/%Y/%m/%d/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_material', to='course.course')),
            ],
        ),
    ]
